// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDmsData = "t_dms_data"

// DmsData mapped from table <t_dms_data>
type DmsData struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DbID       int64          `gorm:"column:db_id;not null;comment:数据库id" json:"db_id"`
	TableName_ string         `gorm:"column:table_name;not null;comment:真实表名" json:"table_name"`
	Name       string         `gorm:"column:name;not null;comment:显示表名" json:"name"`
	Comment    string         `gorm:"column:comment;not null;comment:表注释" json:"comment"`
	Filter     string         `gorm:"column:filter;not null;comment:自定义过滤条件" json:"filter"`
	Sql        string         `gorm:"column:sql;not null;comment:自定义SQL" json:"sql"`
	Sort       string         `gorm:"column:sort;not null;comment:自定义排序" json:"sort"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName DmsData's table name
func (*DmsData) TableName() string {
	return TableNameDmsData
}
